//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewsDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewsDemo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for address.
        /// </summary>
        public static string AddressSearch {
            get {
                return ResourceManager.GetString("AddressSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        public static string Geo {
            get {
                return ResourceManager.GetString("Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geociding.
        /// </summary>
        public static string Geocoding {
            get {
                return ResourceManager.GetString("Geocoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string Hybrid {
            get {
                return ResourceManager.GetString("Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Notified.
        /// </summary>
        public static string LeaderNotified {
            get {
                return ResourceManager.GetString("LeaderNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders.
        /// </summary>
        public static string Leaders {
            get {
                return ResourceManager.GetString("Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any part of the name.
        /// </summary>
        public static string LeaderSearchPlaceholder {
            get {
                return ResourceManager.GetString("LeaderSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting request submitted for {0}.
        /// </summary>
        public static string MeetingSubmittedFor {
            get {
                return ResourceManager.GetString("MeetingSubmittedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received.
        /// </summary>
        public static string MessageReceived {
            get {
                return ResourceManager.GetString("MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leaders available.
        /// </summary>
        public static string NoLeaders {
            get {
                return ResourceManager.GetString("NoLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Received:
        ///Title: {0}
        ///Message: {1}
        ///D: {2}.
        /// </summary>
        public static string NotificationReceivedFor {
            get {
                return ResourceManager.GetString("NotificationReceivedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Leaders.
        /// </summary>
        public static string OurLeaders {
            get {
                return ResourceManager.GetString("OurLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
